#!/usr/bin/env python3
"""Embed a port-owned PNG (src/pc/assets/) as a compiled-in C byte array, so
the native executable carries it with no runtime file dependency.

Only the chunks that make the picture are embedded (KEEP: the image data and
what changes how libpng decodes it) -- an image tool's own metadata (EXIF,
a provenance manifest, text chunks) is stripped, the same policy
tools/pc/embed_controls_art.py already established for ps1-controller.png.

Usage: python3 tools/pc/embed_png_asset.py <name>
  reads  src/pc/assets/<name>.png
  writes src/pc/assets/<name>_png.h  (array name: <name>_png, c-identifier-safe)
"""
import re
import struct
import sys
import zlib
from pathlib import Path

KEEP = {b"IHDR", b"PLTE", b"tRNS", b"gAMA", b"cHRM", b"sRGB", b"iCCP", b"sBIT", b"IDAT", b"IEND"}


def embed(name: str) -> None:
    root = Path(__file__).resolve().parents[2]
    source = root / "src/pc/assets" / f"{name}.png"
    original = source.read_bytes()
    data, at = bytearray(original[:8]), 8
    kept, total = 0, 0
    while at < len(original):
        length, kind = struct.unpack(">I4s", original[at:at + 8])
        chunk = original[at:at + 12 + length]
        if zlib.crc32(chunk[4:8 + length]) != struct.unpack(">I", chunk[8 + length:])[0]:
            raise SystemExit(f"{source}: chunk {kind!r} at {at} fails its CRC")
        total += 1
        if kind in KEEP:
            data += chunk
            kept += 1
        at += 12 + length
    identifier = re.sub(r"[^0-9A-Za-z_]", "_", name)
    out = root / "src/pc/assets" / f"{name}_png.h"
    with out.open("w") as f:
        f.write(f"/* Generated by tools/pc/embed_png_asset.py from {name}.png. Do not edit. */\n")
        f.write(f"static const unsigned char {identifier}_png[] = {{\n")
        for i in range(0, len(data), 24):
            f.write("    " + ",".join(str(b) for b in data[i:i + 24]) + ",\n")
        f.write("};\n")
    print(f"Embedded {len(data)} of {len(original)} bytes ({kept}/{total} chunks kept) "
          f"from {source.relative_to(root)} to {out.relative_to(root)}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} <name>  (reads src/pc/assets/<name>.png)")
    embed(sys.argv[1])
